name: sweyer
description: Open source music player built with Flutter
homepage: https://github.com/nt4f04uNd/sweyer
repository: https://github.com/nt4f04uNd/sweyer
issue_tracker: https://github.com/nt4f04uNd/sweyer/issues
publish_to: none
version: 1.0.1+2
 
environment:
  sdk: ">=2.6.0<3.0.0"
  # Commit 183f0e797a3bf8aa1b35b650150f7522d5d10377
  # flutter: 1.24.0-8.0.pre.374

dependencies:
  # color_thief_flutter: ^1.0.2
  async: ^2.4.0
  animations: ^1.1.2
  fluttertoast: ^7.0.2
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.10
  path_provider: ^1.6.14
  json_annotation: ^3.0.1
  percent_indicator: ^2.1.5
  firebase_core: ^0.5.2+1
  firebase_crashlytics: ^0.2.3+1
  firebase_analytics: ^6.2.0
  package_info: ^0.4.3
  url_launcher: ^5.5.0
  flare_flutter: ^2.0.6
  auto_size_text: ^2.1.0
  marquee: ^1.6.1
  equatable: ^1.2.5
  device_info: ^0.4.2+9
  enum_to_string: ^1.0.14
  sqflite: ^1.3.2+2
  path: ^1.7.0
  flutter_sticky_header: ^0.5.0
  multiple_localization:
    git:
      url: https://github.com/nt4f04uNd/flutter_multiple_localization
  scrollable_positioned_list: ^0.1.9
  # scrollable_positioned_list:
    # path: C:/dev/projects/native/flutter.widgets/packages/scrollable_positioned_list
  nt4f04unds_widgets:
    # path: C:/dev/projects/native/nt4f04unds_widgets 
    git:
      url: https://github.com/nt4f04uNd/nt4f04unds_widgets/
      ref: f14e448d23d347f17c05549972e638d61cf300b4 # version 1.0.3

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5
  # intl_translation: ^0.17.10+1
  intl_translation:
    git:
      url: https://github.com/nt4f04uNd/intl_translation
      ref: 198ba30710a7aeba94813389dac47c9092d11e6c

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
    # don't include a whole folder here because of README  
   - assets/animations/play_pause.flr
   - assets/animations/checkmark.flr

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/manrope-extrabold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/manrope-bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/manrope-semibold.ttf
          weight: 600
